#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Regenerate the case index.

Usage:
    python3 scripts/generate_index.py

What it does:
1. Creates / refreshes a README.md inside every category folder
2. Regenerates cases/README.md with an up-to-date table (category, count, links)

Run it after merging any case PR.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CASES = ROOT / "cases"

CATEGORIES = [
    ("01-thinking-research", "Thinking & Research",
     "研究、分析、推理、信息整理与复杂问题解决",
     "Research, analysis, reasoning, synthesis, complex problem solving"),
    ("02-coding", "Coding",
     "软件开发、Vibe Coding、Debug、重构、Agent Coding",
     "Software development, vibe coding, debugging, refactoring, agent coding"),
    ("03-design", "Design",
     "UI、UX、品牌设计、视觉设计、产品原型",
     "UI, UX, branding, visual design, prototyping"),
    ("04-writing-content", "Writing & Content",
     "文章、公众号、短视频、脚本、知识内容生产",
     "Articles, newsletters, short video, scripts, knowledge production"),
    ("05-data-office", "Data & Office",
     "Excel、数据分析、报告、PPT、Word 与知识工作自动化",
     "Spreadsheets, data analysis, reports, slides, docs, knowledge-work automation"),
    ("06-agent-automation", "Agent & Automation",
     "Agent、Skills、MCP、自动化工作流与 AI 助手",
     "Agents, skills, MCP, automated workflows, AI assistants"),
    ("07-business", "Business",
     "企业经营、市场、销售、客服、运营、管理",
     "Operations, marketing, sales, support, management"),
    ("08-startup-opc", "Startup & OPC",
     "创业、超级个体、One Person Company 与 AI Native Business",
     "Startups, solopreneurs, One Person Company, AI-native business"),
    ("09-education", "Education",
     "教学、课程设计、学习、科研和教育创新",
     "Teaching, course design, learning, research, education innovation"),
    ("10-industry", "Industry",
     "金融、制造、文旅、政务、零售等行业应用",
     "Finance, manufacturing, tourism, government, retail and more"),
]

CATEGORY_README = """# {num}. {en}

> {zh}
> {en_desc}

**收录中 / Cases: {count}**

{listing}

---

## 新增一个案例 / Add a case

1. 复制模板 / Copy the template：[`templates/case-template.md`](../../templates/case-template.md)（[English](../../templates/case-template.en.md)）
2. 文件名用英文 kebab-case / Use English kebab-case，例如 `from-idea-to-webapp.md`
3. 放进本目录 / Put it in this folder，然后提 PR / then open a PR

完整规范见 / Full rules: [`CONTRIBUTING.md`](../../CONTRIBUTING.md)

[← 返回案例总目录 / Back to index](README.md)
"""

INDEX_HEAD = """# Cases

GPT-6 真实案例索引。**目前共 {total} 个案例。**
Index of real GPT-6 cases. **{total} cases so far.**

| 分类 / Category | 案例数 / Cases | 说明 / What's inside |
| --- | --- | --- |
"""

INDEX_TAIL = """
## 如何新增 / How to add one

1. 复制 [`../templates/case-template.md`](../templates/case-template.md)（[English](../templates/case-template.en.md)）
2. 按上面的分类放进对应目录，文件名用英文 kebab-case
3. 提 PR，标题用 `case(<分类>): <案例名>`

详细规范见 [`../CONTRIBUTING.md`](../CONTRIBUTING.md)（[English](../CONTRIBUTING.en.md)）。

> 本文件由 `scripts/generate_index.py` 自动生成，合并案例后重跑即可刷新。
> This file is generated by `scripts/generate_index.py` — rerun it after merging a case.
"""


def list_cases(folder: Path):
    return sorted(
        p for p in folder.glob("*.md")
        if p.name.lower() != "readme.md"
    )


def human_title(path: Path) -> str:
    return path.stem.replace("-", " ").strip().capitalize()


def ensure_dir(path: Path) -> None:
    # exist_ok=True is unreliable behind some sandboxes, so check first
    if not path.exists():
        path.mkdir(parents=True)


def main() -> None:
    ensure_dir(CASES)
    total = 0

    for folder_name, en, zh, en_desc in CATEGORIES:
        folder = CASES / folder_name
        ensure_dir(folder)
        cases = list_cases(folder)
        total += len(cases)

        if cases:
            listing = "\n".join(f"- [{human_title(p)}]({p.name})" for p in cases)
        else:
            listing = "_暂无案例，等你来写第一个。No cases yet — write the first one._"

        num = folder_name.split("-")[0]
        (folder / "README.md").write_text(
            CATEGORY_README.format(
                num=num, en=en, zh=zh, en_desc=en_desc,
                count=len(cases), listing=listing,
            ),
            encoding="utf-8",
        )

    rows = []
    for folder_name, en, zh, en_desc in CATEGORIES:
        count = len(list_cases(CASES / folder_name))
        rows.append(
            f"| [{en}]({folder_name}/) | {count} | {zh} |"
        )

    (CASES / "README.md").write_text(
        INDEX_HEAD.format(total=total) + "\n".join(rows) + "\n" + INDEX_TAIL,
        encoding="utf-8",
    )
    print(f"index updated: {total} cases in {len(CATEGORIES)} categories")


if __name__ == "__main__":
    main()
